### ISSUE TITLE
images with too high or too wide

### ISSUE THREAD

**Issue by pool611** [mcstudios/glightbox#1]
if image is too high or too wide，it can't see the whole image. dragging image is not usefull to see the whole image. could you consider this question?
thank you

**Comment by mcstudios** [comment]
Can you tell which browser are you using? there's definitely something happening but the image should never grow bigger than the browser window. 

Take a look at the video below, the image displayed has a width of 3800px and height of 2533px and the browser window was about 1700px width, still there's something happening [Watch Video](https://www.youtube.com/watch?v=xc15CMD3dCc&feature=youtu.be)

I'll take a look at this and fix it.

**Comment by mcstudios** [comment]
If you have a chance give a try to the latest version and let me know if that works for you

**Comment by pool611** [comment]
Yep，image is resized by the phone‘s screen now.
Thanks again
There is another image's situation on the phone like this: 
![long-screenshot-on-oppo-f1-271x1024](https://user-images.githubusercontent.com/10056712/34806345-639995ca-f6bd-11e7-934e-122ea93f7680.png)
Long screenshot is too long and if resizing it, it becomes smaller and the text could not be see clearly.
Whether Special support should be given to such images？Only the width fits the screen and it is supported to Gestures sliding to view image？
Looking forward to your reply.
sorry, I forget to say last time that I test it on the phone , not PC .

**Comment by mcstudios** [comment]
Well for this kind of images shrinking the image to fit the device screen is not the best approach. I think that if the image is really long then we should fit only the image width with the screen and let the user drag (scroll) the image with one finger, let me know what you think or if you have a better idea.

**Comment by pool611** [comment]
That's what I think. May be better that if height/width(image) > height/width(screen), using the new way(drag or scroll) to view image, if height/width(image) <= height/width(screen), using the present way(shrink the image to fit the device screen) to view image.
:)
