### ISSUE TITLE
sourcetype wrong. Can we manually set sourcetype?

### ISSUE THREAD

**Issue by ndimatteo** [mcstudios/glightbox#12]
It seems that the `sourcetype` is incorrectly applied when using certain URLs. For example when using images from unsplash.it, which look like this: `https://unsplash.it/1200/800` it thinks it's an `iframe` when in fact, it's an `image`.

It would be great if there was a way to set the `sourcetype` manually, rather than have the plugin guess, as it's not fully reliable.

perhaps an option of `type: 'image' | 'iframe' | 'video' | 'inline'`

**Comment by mcstudios** [comment]
Published version 1.0.6, now you can specify the type of the element using data-glightbox="type: image"

Let me know if this helps :)

**Comment by evanwarner** [comment]
Just wanted to say I came here with this same problem because the CMS I use can re-crop images on the fly and the crops were showing in iframes. This solved it perfectly so thank you!!!

**Comment by userofit123** [comment]
I am having this same issue and have tried this fix, but it is not working for me.

I am trying to load an image, but it is loading it in an iframe.
Any ideas on how to fix this?
