### ISSUE TITLE
Add method for open custom popup

### ISSUE THREAD

**Issue by musiclover174** [mcstudios/glightbox#13]
like fancybox $.fancybox.open({})

or i blind and this method are realized?

and be very cool if i can call popup manually gallery.open() or else

**Comment by mcstudios** [comment]
Published version 1.0.6, please download again and check [the api section](https://glightbox.mcstudios.com.mx/#api) 

Also a new method was added "setElements" 

Let me know if this helps you :)

**Comment by musiclover174** [comment]
Good job.
And some more else:
Do you have in plans make grouped elems by data-attr?
I want to initialize ligthbox one for one similar class and have other groups. In current realizations elems grouped by class and i must initialize twice if i want 2 different groups on one page

**Comment by mcstudios** [comment]
You can use  data-gallery="yourname" to group the images in multiple sets
