### ISSUE TITLE
rebind after ajax?

### ISSUE THREAD

**Issue by 1ucay** [mcstudios/glightbox#15]
Hi, I have dynamic content via ajax. How can I rebind glightbox? Thank you

**Comment by mcstudios** [comment]
I'm currently working on a project that uses ajax to load a portfolio so I was planning to update GLightbox to make it easier on this cases, for example:

```
// Initial Lightbox instance
var lightbox = GLightbox({
    selector: 'mylinks',
    ....
});

myAjaxLoadNewContent(function() {

    // When the new content is added we just need
    // to tell GLightbox to reload and attach the required events to
    // new elements 

    lightbox.reload();

});
```

I'm still working on this, let me know what you think.

**Comment by MilenFrom** [comment]
Is there any progress on that?
On success I'm destroying the previous glightbox and reinitiate.
However I think this isn't the best solutions.

**Comment by MilenFrom** [comment]
I made a screencast, after ajax request can't load the previous photos
https://youtu.be/iEstrWkUEtg

**Comment by mcstudios** [comment]
Sorry for the delay guys. The reload method has been added so you can try it and let me know how it goes

**Comment by chicocheco** [comment]
Hi, thank you for adding the **.reload()** method. Unfortunately, it does not work for me. When there is an ajax call to load more content on the background while the glightbox is open I call the reload method the next slide button is still greyed out although I can press the arrow key and it seems to be working at first but the following images are not loaded in the lightbox. There a loading animation and it never finishes. The only solution is to close the lightbox and open it again

![image](https://user-images.githubusercontent.com/33058002/156995041-a4ee4a83-9030-4cb0-9562-4fe27124efe7.png)

Is there I way of adding new slides without having to close and open the lightbox every time a new content is loaded?
Thank you very much

**Comment by frankie-tech** [comment]
> Is there I way of adding new slides without having to close and open the lightbox every time a new content is loaded?

GLightbox has the insertSlide method. This will just add a slide to the end of the array of slides, or insert it into a specific index.

**Comment by chicocheco** [comment]
Thanks! I didn't realize I could simply call this method after adding every new element on page. I spent hours playing around with it (don't know much of JS), what a disaster, haha
