### ISSUE TITLE
Close Button can't be disabled

### ISSUE THREAD

**Issue by mittermayr** [mcstudios/glightbox#16]
While there's a setting for it, it seems not to be taken into account when disabled.

```
var myLightbox = GLightbox({
  'selector': 'lightbox',
  closeButton: false,
}); 
```

Still shows the closeButton. I checked the code and it does only seem to attach an event to it, or not, based on that setting. Am I wrong?

**Comment by mcstudios** [comment]
You are right, that was solved in the lates update, 1.0.7. The setting will now correctly remove the close button.
