### ISSUE TITLE
image can't show by initialized more times

### ISSUE THREAD

**Issue by pool611** [mcstudios/glightbox#2]
when I initialized GLightbox twice or more，images would not show any more. Because I use ajax to refresh or page load the webview, so GLightbox may be initialized more times. It may be that I use it incorrectly.
:(

**Comment by mcstudios** [comment]
We have used Glightbox before with ajax without problems, can you send us a link or shows us your code to see what's happening?

**Comment by pool611** [comment]
em...
For example that I use Vue to bind data:
`
<div v-for="url in imageList">
  <a v-bind:href="url" class="glightbox">
    <img v-bind:src="url"/>
  </a>
</div>
<script type="text/javascript">
new Vue({
    ...
    data:{
         imageList:["1.png"],
    },
    methods:{
        refresh function(imageListData){
             // Get imageListData by ajax to refresh imageList
             // Before  imageList : [ "1.png"] , after imageList :["1.png" , "2.png"]
             imageList = imageListData; 
             // Second initialize, 2.png can show, 1.png can't show
             // There are too much "glightbox-body" in html for 1.png
             var lightbox = GLightbox(); 
        }
    }
});
...
var lightbox = GLightbox();// First initialize, 1.png can show
</script>
`

**Comment by pool611** [comment]
```
...
init(){
        this.baseEvents = addEvent('click', {
            onElement: `.${this.settings.selector}`,
            withCallback: (e, target) => {
                e.preventDefault();
                this.open(target);
            }
        });
        // I need this,then I can destroy glightbox
        return this;
}
...
```

**Comment by 1ucay** [comment]
I have same problem...

**Comment by CNK001** [comment]
me too, do you how to force reload after each render?

**Comment by puzrin** [comment]
@biati-digital 

> We have used Glightbox before with ajax without problems, can you send us a link or shows us your code to see what's happening?

We got this issue, when assigned 2 create handlers by mistake, and click caused two `glightbox(elements).openAt(x)` invocation by mistake. It would be nice to throw comprehensive error on such case, if possible.
