### ISSUE TITLE
The video does not work in mobile devices

### ISSUE THREAD

**Issue by yhensel** [mcstudios/glightbox#20]
I was trying to use your library but when I load the page in my iPhone 7, the videos is not being showed, the screen rest in black. 

I thoungt there was a problem with my devise so I did the same in Firefox with the same result. After try it out in the page I'm actually developing I also did it with your demo. And the problem remains

**Comment by designspin** [comment]
I've just checked out the demo on the glightbox website using my iPhone 7. It appears the vimeo and youtube videos do not work. The buck bunny example works just fine.

**Comment by ezebecke** [comment]
@designspin go to the CSS file and change this property:

`iframe.wait-autoplay {
  opacity: 0;
}`

opacity should be 1:
`iframe.wait-autoplay {
  opacity: 1;
}`

**Comment by designspin** [comment]
@ezebecke , thanks i'll give it a go. This is going to be a real time saver on a current project. Thanks mcstudios for all your hard work.

**Comment by WilliamRayo** [comment]
@ezebecke i had the same problem, your solution works perfectly !! thanks ;)

**Comment by mcstudios** [comment]
Hi guys, please try the latest update 1.0.7, this error should be fixed there.
