### ISSUE TITLE
Regex on src for images

### ISSUE THREAD

**Issue by designspin** [mcstudios/glightbox#21]
I was playing with glightbox yesterday and discovered that if the src of your image has any params it will end up in an iframe and treated as a video.

Looking at the code it looks like the regex check is just checking the end of a string for '.jpg' or '.jpeg' etc....

For my current project i am using urls that have params such as 'https://somesite/somefile.jpg?mtime=023473663', in these cases the script does not recognise as an image. I got around this by using a regex in my template to remove the 'mtime' param which probably is not ideal.

**Comment by mcstudios** [comment]
Hi, for those kind of situations you can define the type you want, take a look at this [issue](https://github.com/mcstudios/glightbox/issues/12)

Let me know if this helps.

**Comment by designspin** [comment]
Awesome, that does look like it would resolve my issue. Many thanks.
