### ISSUE TITLE
Scrolling to top of browser.

### ISSUE THREAD

**Issue by designspin** [mcstudios/glightbox#22]
When clicking an item in my gallery the browser moving to the top of the browser. Is there a way to prevent this? I see the demo site does not show this behaviour so it is something I am doing wrong!

I tried adding a preventDefault on the anchor containing the gallery image!

**Comment by awps** [comment]
Same here. Any solutions on this?

**Comment by mcstudios** [comment]
Could you guys post a link to a live example, maybe sharing browser info or any information that helps to figure out what's happening?

**Comment by nickdekruijk** [comment]
Your own demo page has this issue! (Safari on MacOS)

**Comment by mcstudios** [comment]
Well, I'm checking it on safari (Mac os) and not able to see that error, take a look at this [video](http://youtu.be/nTf4qRaX27A)

I'm gonna need some help with this, already tried in safari, chrome, opera and firefox but I'm not able to replicate that error.

**Comment by nickdekruijk** [comment]
Hmm... I was sure I've seen it on your demo site too, can't reproduce that now tho.
But check out this site: https://bit.ly/2NHHAll scroll down a bit and click the play video button.

**Comment by losbeekos** [comment]
I've got a bug that's somewhat related to this.

On mobile it's still possible to scroll the body when the lightbox is open, just scroll a bit slanted and the page gets scrolled behind the lightbox.

@mcstudios You got an idea so I can resolve this quickly?

**Comment by englishextra** [comment]
@mcstudios @nickdekruijk @awps 

It's not the way it is described above.

The source code adds class to `<html>` and `<body>`:
```js
key: 'open',
					value: function open() {
						var element = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : null;
						this.elements = this.getElements(element);
						if (this.elements.length == 0)
							return false;
						this.activeSlide = null;
						this.prevActiveSlideIndex = null;
						this.prevActiveSlide = null;
						var index = this.settings.startAt;
						if (element) {
							// if element passed, get the index
							index = this.elements.indexOf(element);
							if (index < 0) {
								index = 0;
							}
						}
						this.build();
						animateElement(this.overlay, this.settings.openEffect == 'none' ? 'none' : this.settings.cssEfects.fade.in);
						var bodyWidth = body.offsetWidth;
						body.style.width = bodyWidth + 'px';
						addClass(body, 'glightbox-open');
						addClass(html, 'glightbox-open');
```
and this class riuns your setup.
```css
 height: auto;
```

If your base css has:

```css
html,
body {
	height: 100%;
}
```

you should keep it, and not spoil it:

```css
/*!
 * @see {@link https://github.com/mcstudios/glightbox/issues/22}
 */

.glightbox-open {
	height: 100% !important;
}
```

**Comment by rlidwka** [comment]
Same issue here.

I noticed that scroll happens when overflow property gets changed, so I solved it with:

```
html.glightbox-open {
  overflow: initial;
}
```

(note `html` tag restriction, overflow works fine on `body` tag)

**Comment by joehuggans** [comment]
Wondering if this is marked as fixed? It only happens for me on devices 768px and below. Seems to be related to

@media (min-width: 769px) {
.glightbox-open {
    height: auto;
}
}

**Comment by corzel** [comment]
Hi, I fix it by changing the overflow on line 416 of the CSS to "visible".

```
.glightbox-open {
  overflow: visible;
}
```

**Comment by jafarfaris** [comment]
> > Same issue here.
> > I noticed that scroll happens when overflow property gets changed, so I solved it with:
> > ```
> > html.glightbox-open {
> >   overflow: initial;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (note `html` tag restriction, overflow works fine on `body` tag)
> 
> this works great! thank you.

is not working for me,, already in late 2024, but still not fixed
how to fix it?

**Comment by gingerchew** [comment]
@jafarfaris 
> is not working for me,, already in late 2024, but still not fixed how to fix it?

This is a 6 year old issue. Please make a new one using the issue templates provided and a codepen and we can take another look at it.
