### ISSUE TITLE
Should add option to force image from cdn

### ISSUE THREAD

**Issue by dominik-wbz** [mcstudios/glightbox#23]
Some cdn eg. uploadcare has images in url without extension e.g. https://ucarecdn.com/90964191-dfa2-4a22-8118-8a9e460fff9b/

This then causes the image to appear in iframe as this condition fails:

`if (url.match(/\.(jpeg|jpg|gif|png)$/) !== null)`

I added a temporal solution for my project

`if (url.match(/\.(jpeg|jpg|gif|png)$/) !== null || url.match(/ucarecdn.com/))`

Would be nice to implement force option to show images without extension needed

**Comment by mcstudios** [comment]
Already answered [here](https://github.com/mcstudios/glightbox/issues/12) and [here](https://github.com/mcstudios/glightbox/issues/21)
