### ISSUE TITLE
Duplicate ids in div lightbox

### ISSUE THREAD

**Issue by victor-in** [mcstudios/glightbox#24]
I have a form inside a div which is then displayed using the lightbox. When opened glightbox duplicates the div to show the content. This causes issues with ids, since they also get duplicated and aren't unique anymore.

For example label elements using the for-attribute stop working as well as assigned event-listeners.

Maybe moving the div instead of duplicating it could solve this.

Cheers,
Victor

**Comment by mcstudios** [comment]
Hi, not sure that's a good solution, moving the div out of it's container could cause problems like (losing css style, losing event listeners, etc.) GLightbox can be applied to many type of elements so moving the element is not an option.

I recommend you that you listen the open method and you could manipulate your form, for example:

```javascript
var lightbox = GLightbox({
      selector: 'form'
});
lightbox.onOpen(function() {
    // a.- Change the original form ids temporarily and restore them on close
    // b.- Clone the original form and store it in a variable, remove the original form and when the lightbox is closed just insert the cloned form
    // c.- Well there are many ways to handle this... like changing the ids of the form in the lightbox, etc. 
})
```

Hope this helps
