### ISSUE TITLE
Request: determine length of gallery by unique slides not triggers

### ISSUE THREAD

**Issue by evanwarner** [mcstudios/glightbox#25]
My use case: building an event calendar and using glightbox to show event details (from a hidden in-page element) when events are clicked.

In this case, there are repeating events where each instance on the calendar points to the same details. But since glightbox controls the length of a gallery by how many triggers it has, what I get is a slideshow that contains the same details container X times (one for each event repeat). What I would love is if glightbox identified duplicate slides and only instantiated one copy, letting all triggers that point to it open the slideshow at that point.

**Comment by mcstudios** [comment]
Hi, you can controls the elements in the gallery passing them in the options for example: 

```javascript
var lightbox = GLightbox({
    elements: [
        {
            'href': 'https://picsum.photos/1200/800',
            'type': 'image'
        },
        {
            'href': 'https://www.youtube.com/watch?v=Ga6RYejo6Hk',
            'type': 'video',
            'source': 'youtube', //vimeo, youtube or local
            'width': 900,
            'height': 560
         }
      ]
});
```

Then you can open the gallery with lightbox.open() or you can overwrite the elements in the gallery using lightbox.setElements([..check the above example]);

Let me know if this helps.
