### ISSUE TITLE
Autoplay issue: Youtube

### ISSUE THREAD

**Issue by rob-anythingagency** [mcstudios/glightbox#26]
Hi,

I am experiencing an autoplay issue on youtube embeds (desktop). 

When first opening the lightbox the youtube video will not autoplay, if you close the lightbox and then re-open it the video will now autoplay.

This happens both in my code and on your example website (the issue doesn't effect the Vimeo or JW player options).

Any idea of the cause?

Thanks

**Comment by mcstudios** [comment]
When you open the video for the first time it will load the required API (youtube, vimeo, jwplayer, etc.) Once the api is loaded it will autoplay|pause|stop using the methods from the api.

I'm not able to replicate the error so it's going to be a little difficult to know what's happening but i'll try to replicate it.

**Comment by rob-anythingagency** [comment]
Hi, Thanks for the reply.

To replicate:

Go to: https://glightbox.mcstudios.com.mx/
Scroll to Videos Gallery
Click on middle thumbnail
Lightbox will open with embed, but will not autoplay (at least it doesn't for me)
Click to dismiss
Click on middle thumbmail again
Lightbox will open with embed, this time it will autoplay

I would expect it to autoplay on the first open, if the autoplay options have been set.

Hopefully this helps you see the issue?

Thanks again

**Comment by mcstudios** [comment]
Closing this for now, feel free to open a new issue if required
