### ISSUE TITLE
Can't use : or ; sign in description text

### ISSUE THREAD

**Issue by nickdekruijk** [mcstudios/glightbox#30]
How can I get something like this to work?

`data-glightbox="title:Test; description: size: M<br>price: 100"`

Can't use : or ; sign in description text since it's also used to split the options.
One suggestion would be to make \: work or :: is replaced with a single : or something.

Actually I think it would be better to give each option it's own data property? For example 
`data-glightbox-title="Title" data-glightbox-description="size: M<br>price: 100"`

**Comment by mcstudios** [comment]
You can't use : or ; there but you can create a div with the class "glightbox-desc" and put anything you want in there, check the Images with description example in the index.html file (the second element).

Let me know if that helps.

**Comment by nickdekruijk** [comment]
I tried it, but that means having a <div> tag inside a <a> tag, which is just a bad idea. Also that means I can't use my own links inside the description since adding a </a> tag inside the glightbox-desc div will break the main <a> tag that opens the glightbox

**Comment by mcstudios** [comment]
You are right, the div is not the best solution, we need to think a solution to handle : and ; within the data parameter. If you have any idea let me know, this is something that will benefit a lot of people so i'm open to make some changes to make it work.

Another "solution" is to pass the elements directly to the lightbox like:

```javascript
var lightboxDescription = GLightbox({
      selector: 'glightbox2'
});
lightboxDescription.setElements([
        {
          'href': 'image here',
          'title': 'title',
          'description': 'size: M<br>price: 100'
        },
        ....
]);
```
The problem with this approach is that the lightbox will always open in the first slide, you can use the api to manipulate the active slide "lightboxDescription.goToSlide(2);", etc. It seems to much to solve a simple problem with two characters but just trying to give some ideas.

**Comment by nickdekruijk** [comment]
The problem isn't actually using those 2 characters. I just used that example to simplify the example. The real issue is that I want to be able to add links in the description. And links often have : in it (https:// or mailto: for example)

**Comment by mcstudios** [comment]
Not sure why https:// or mailto: are a different problem. No matter the string you use, if you put : or ; it will break. GLightbox only looks for those characters to split the string.

I had an idea to split the string without using those characters as reference but i'm not gonna be able to work on this till next week, this will fix this issue. One thing that i wanted when creating GLightbox was to avoid too many data parameters but i think this is doable and still maintain the single data parameter option so i'll work on this next week.

BTW, I tried the url without the : character and it shows correctly [View image] (If i understand you corretcly)(http://drops.mcstudios.s3.amazonaws.com/Screen-Shot-2018-09-14-at-9.02.05-AM.png)

For reference the code used was:
`data-glightbox="title:Description Bottom; description: You can set the position of the desciption <br> <a href='https//google.com'>click me</a>"`

**Comment by mcstudios** [comment]
I've fixed the problem with : or ; characters also the latest version (1.0.8) now allows you to use different data attributes for example data-title="Lightbox title" data-description="my description"

Please try it and let me know how it works.

**Comment by mcstudios** [comment]
Closing this for now, feel free to open new issues if required
