### ISSUE TITLE
Where are the cdn hosted files

### ISSUE THREAD

**Issue by drnkwati** [mcstudios/glightbox#34]
Hi
please can the files be hosted on a cdn
i suggest cdnjs and jsdelivr
thanks

**Comment by MartinKolarik** [comment]
It's available at jsDelivr: https://cdn.jsdelivr.net/gh/mcstudios/glightbox/dist/js/glightbox.min.js all other files from this repository are there too.

**Comment by drnkwati** [comment]
Yeh I figured that out today.
Thanks and good job.
