### ISSUE TITLE
prevent page from jumping top when glightbox opens

### ISSUE THREAD

**Issue by remi-smoothlane** [mcstudios/glightbox#36]
Hello,

I got one minor issue that makes the page jumps top when the lightbox opens up. I've tried few things like adding `e.preventDefault();` when clicking on the lightbox ClassName but it doesn't seems to do the trick.

Any idea where this issue could come from ?

Many thanks

**Comment by mcstudios** [comment]
Hi, please check this closed [issue](https://github.com/mcstudios/glightbox/issues/22)

**Comment by remi-smoothlane** [comment]
Problem solved. Thank you

**Comment by mcstudios** [comment]
No problem :)
