### ISSUE TITLE
npm package too big for jsDelivr

### ISSUE THREAD

**Issue by gitrequests** [mcstudios/glightbox#38]
I'm trying to load this package from [jsDelivr CDN](https://www.jsdelivr.com/package/npm/glightbox) but it fails because the package is over 50 MB. Are there any files that could be removed to reduce the package size?

**Comment by MartinKolarik** [comment]
The whole `demo` directory should be excluded from npm.

**Comment by mcstudios** [comment]
Excluded the demo directory from npm, i'll publish the update today.
