### ISSUE TITLE
Turn off moreText a tag

### ISSUE THREAD

**Issue by moxdev** [mcstudios/glightbox#4]
Is there a way to disable to desc-more link so it shows the full description while in mobile? I want it to show the full description without having to click the see more link.

**Comment by mcstudios** [comment]
We have added a new option called moreLength, you can configure the number of characters to display in the description before the moreText a tag, if you enter 0 (int) the entire description will be displayed.

Please download again and try it.

**Comment by moxdev** [comment]
Brilliant! Its working fine thank you for the quick response!
