### ISSUE TITLE
Lightbox won't fit screen with description

### ISSUE THREAD

**Issue by nickdekruijk** [mcstudios/glightbox#44]
See this example: https://peterblokland.nl/gallery and click the first image. The description won't fit the screen because the image is too large. Your own demo site has this issue too, make your browser window smaller and open the image with the man with the hat which has a bottom description. With description left or right it works fine.

Edit: Since my example was a live site I disabled descriptions for now (I don't like left/right) but this is what your demo site looks like on smaller screens, description is falling off because image isn't resized properly:
![schermafbeelding 2019-01-14 om 13 52 21](https://user-images.githubusercontent.com/607302/51113806-a6910080-1803-11e9-9598-95ccb039a555.png)

**Comment by mcstudios** [comment]
Hi @nickdekruijk i've added some fixes and this should be working now, could you please try it and let me know?

*Still not published in the releases page just download the code instead.

**Comment by mcstudios** [comment]
I'm closing this for now as i never heard of you, feel free to open any new issues if you find a bug.
