### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by connor-wilson-dev** [mcstudios/glightbox#45]
So I love this library, first off.
It was working fine through out the website I'm building but now, out of nowhere, it's saying that the maximum call stack size is being exceeded.

Step 1
open lightbox with images and videos.
Step 2
Move to video
Step 3
Video won't load
Step 4
Move to slide before video and back again, video loads fine.

I have another gallery on the page that has videos on it too. But I'm assuming since its a different instance of GLightbox that it shouldn't be causing any issues.

This is my code for the lightbox I'm having an error with.
```js
const youtubeObj = {
    api: "https://www.youtube.com/iframe_api",
    params: {
        enablejsapi: 1, //use jsApi
        showinfo:1, //Show info about the video
        rel:0 //Show related videos from youtube or from channel (0 equals channel, 1 equals youtube)
    }
}

$(document).ready(function() {

    const lightbox = GLightbox({
        youtube: youtubeObj
    });

});
```
Let me know if you need any other information to help with this

**Comment by mcstudios** [comment]
Hi @connor-wilson-dev i'm glad you like this library. We made some changes so autoplay works correctly when changing slides, please download the code again and try it.

I'm not able to replicate the Maximum call stack size exceeded error, do you have a working example?

**Comment by connor-wilson-dev** [comment]
I will see if I can spin up a jsFiddle or something. I'm not even sure where the issue is, I just got into work, so I should be able to do it around lunch time

**Comment by connor-wilson-dev** [comment]
sorry for the late response, deadlines, am i right?

anyways here's the codepen

https://codepen.io/webinternconnor/pen/RvyyEr

I tried to create it as simple and basic as possible.
Basically, the gallery is a simple gallery, it shows x amount of images to potential customers, and then hides y amount of images to be seen if the light gallery is opened

hopefully this helps

**Comment by mcstudios** [comment]
Hi @connor-wilson-dev 

Thanks for the example but the demo it's using an older version, like i said in my previous comment, the video problem should be fixed in the latest update v2.0.0 (still not published as a release so just download the code) please download it again, try it and let me know if it's working fine.

About the error "Maximum call stack size exceeded", if we're not able to replicate it in the demo, it's gonna be hard to find what's happening, i've never seen that error with this library but if you see it again let me know.

**Comment by connor-wilson-dev** [comment]
I totally missed that when I first read it, I'll change that out.

I figured without a stacktrace it would be hard to solve, but thanks for helping out anyways!

**Comment by mcstudios** [comment]
No problem, if you have time you are welcome to submit a pr, for now i don't have time to investigate that error, i'm closing this for now, feel free to open any new issues if you find a problem with this library.
