### ISSUE TITLE
iframe not centered

### ISSUE THREAD

**Issue by nickdekruijk** [mcstudios/glightbox#47]
**Describe the bug**
iframe not centered but left aligned in a 100% width white window in 2.0 version. Used to work fine in older versions

**Are you able to reproduce the bug in the demo site**
Yes

**To Reproduce**
1. Go to https://mcstudios.github.io/glightbox/ section IFRAMES AND INLINE ELEMENTS
2. Click on the middle image (grass) that opens the google maps iframe
3. It's left aligned and with lots of whitespace on the right.

**Expected behavior**
Should be centered

**Screenshots**
![image](https://user-images.githubusercontent.com/607302/53097569-16408c80-3522-11e9-82dd-576d946ab7eb.png)

**Desktop:**
 - OS: MacOS Mojave
 - In Chrome and Safari

**Comment by mcstudios** [comment]
This issue has been fixed in the latest version 2.0.1, please download again and try it.
