### ISSUE TITLE
Close lightbox by clicking anywhere off of the image

### ISSUE THREAD

**Issue by moxdev** [mcstudios/glightbox#5]
We want to be able to close the lightbox by clicking anywhere off of the image instead of just clicking the close button. Is there an option for that or would I have to add some custom js?

**Comment by mcstudios** [comment]
There's no option for that but you can attach an event listener when the lightbox is opened for example: 

```javascript
GLightbox({
  onOpen: function() {
      document.body.addEventListener('click', function(e) {
        var clicked = e.target;
        // check if the clicked element is outside the active div .ginner-container
        // if outslide then call the close method 
      });
  },
  onClose: function() {
     //remove the event listener
  }
})
```

That's just an idea, Let me know if this helps.

**Comment by moxdev** [comment]
Thanks for the head start I was able to get it working. Thanks again for the quick reply and glightbox is a great library!
