### ISSUE TITLE
Touch not working on ios

### ISSUE THREAD

**Issue by Lasergunspewpew** [mcstudios/glightbox#50]
**Describe the bug**
No swipe (touch) functionality to switch between pictures. 
Tested on Iphone X, XS, Ipad Pro 2018. 

**Are you able to reproduce the bug in the demo site**
Yes

**To Reproduce**
1. Open demo page
2. Open picture
3. Try to swipe to get to the next / previous picture

**Expected behavior**
Swiping left/right would load the previous or next picture

**Smartphone:**
 - Device: iPhoneX / XS / ipad Pro 
 - OS: iOS12.1.4
 - Browser Stock Safari.+ Firefox

**Comment by mcstudios** [comment]
I'm working on an update, it will be ready tomorrow.

**Comment by Lasergunspewpew** [comment]
Awesome! Thanks for the quick reply and your work!

**Comment by Lasergunspewpew** [comment]
Any updates? 
Can i offer some help?

**Comment by billmn** [comment]
Same issue for me ... 😢

**Comment by connorwilsonexceleron** [comment]
I to am having an issue, but I'm glad to hear someone is working on it!

**Comment by connorwilsonexceleron** [comment]
I don't know if this will help, when inspecting the page with chrome devtools in phone (iPhone X specifically) the console pushes an error `Body is not defined`

If I try to 'swipe' the image, it will show that error every tick for as much as the mouse is down and moving over the image.

**Comment by mcstudios** [comment]
This issue has been fixed in the latest version 2.0.1, please download again and try it.
