### ISSUE TITLE
fade openEffect and closeEffect don't work

### ISSUE THREAD

**Issue by nickdekruijk** [mcstudios/glightbox#7]
Testing out the fade openEffect (don't really like zoom) but it only seems to fade the modal background and not the image itself.
Changing closeEffect doesn't seem to have any effect, it will always zoom out.

Personally I might prefer no effect at all, just hard show/hide. Maybe a suggestion for next update?

**Comment by mcstudios** [comment]
I'll take a look at that, the no effect option will be added in the next update :)

**Comment by nickdekruijk** [comment]
@mcstudios Cheers!
Another idea: Close the lightbox when you click on the entire background, and not just the close button. Or even better (for me at least) clicking on an image closes it too. Optional of course.

**Comment by mcstudios** [comment]
That was commented before [here](https://github.com/mcstudios/glightbox/issues/5), i'll give it a try, i always press the esc key to close the lightbox so never consider it before. if i'm able to do it with a small amount of code i'll include it.

**Comment by nickdekruijk** [comment]
Seems to work! Thanks for the update.
Btw. On your demo usage and options page (http://glightbox.mcstudios.com.mx) 'CloseButton' option is shown twice.

**Comment by mcstudios** [comment]
Thank's all fix that, i'll close this now, if you have any other issue or request, feel free to open a issue. :)
