### ISSUE TITLE
publish on npm

### ISSUE THREAD

**Issue by lucidlemon** [mcstudios/glightbox#9]
would be great if this package could be pushed to npm so we can install it easier.

**Comment by mcstudios** [comment]
Working on that :)

**Comment by lucidlemon** [comment]
https://docs.npmjs.com/getting-started/publishing-npm-packages

this is a 2 minute process and would help your module grow by at least 1337%.

**Comment by mcstudios** [comment]
Sorry for not getting back to you earlier.

GLightbox was published on npm, please check the updated description and let me know how it goes.

**Comment by lucidlemon** [comment]
yep works. thanks!
